name: Java Version Check

on: [push]

jobs:
  check-java-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Print Java version
      run: |
        echo JAVA_HOME=$JAVA_HOME
        java -version
